[build.hooks.vcs]
dependencies = ["hatch-vcs>=0.4.0"]
version-file = "src/codegen/sdk/__init__.py"

[metadata]
allow-direct-references = true
[envs.hatch-build]
installer = "uv"
[[envs.hatch-build.matrix]]
tool = ["uv", "pip"]

[envs.hatch-build.overrides]
matrix.tool.installer = { value = "{matrix:tool}" }
matrix.tool.scripts = [
    { key = "pip", value = "{env:HATCH_UV} pip {args}", if = [
        "uv",
    ] },
]

[version]
source = "vcs"

[envs.hatch-build.env-vars]
UV_EXTRA_INDEX_URL = "https://aws@codegen-922078275900.d.codeartifact.us-east-1.amazonaws.com/pypi/codegen/simple/"

[build.targets.wheel.hooks.cython]
dependencies = [
    "hatch-cython @ git+https://github.com/codegen-sh/hatch-cython.git",
    "cython>=3.0.11",
    "tree-sitter",
    "networkx",
]

[build.targets.wheel.hooks.cython.options]
src = "codegen/sdk"
compile_args = [
    "-O3",
    { platforms = [
        "darwin",
    ], arch = "arm64", arg = "-mcpu=apple-m1" },
]
cythonize_kwargs = { annotate = true, nthreads = 16, exclude_failures = false, cache = true }
compiled_sdist = true
compile_py = false
compile_parallel = true

[build.targets.wheel.hooks.cython.options.directives]
boundscheck = false
nonecheck = false
language_level = 3
binding = true
linetrace = true
embedsignature = true
profile = true
c_string_encoding = "default"
c_string_type = "unicode"

[build.targets.wheel.hooks.cython.options.files]
exclude = [
    "**/__init__.py",
    "**/code_generation",
    "**/skills",
    "**/codebase/factory",
    "**/guides",
    "**/testing",
    "**/codebase_graph_utils.py",
]

[build.targets.wheel]
macos-max-compat = false

[build]
packages = [
    "src/codegen",
]

[metadata.hooks.vcs]
Homepage = "https://github.com/codegen-sh/codegen-sdk"
source_archive = "https://github.com/codegen-sh/codegen-sdk/archive/{commit_hash}.zip"


[build.targets.wheel.hooks.custom]
enable-by-default = false
path = "src/codegen/gsbuild/build.py"
require-runtime-dependencies = true
[envs.default]
installer = "uv"
