name: report
description: "Publish Junit Report"

runs:
  using: "composite"
  steps:
    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results-${{github.run_id}}-${{github.job}}-${{ join(matrix.*, ' - ') }}
        path: '**/build/test-results/test/TEST.xml'
        retention-days: 1
    - name: Download Test Report
      uses: actions/download-artifact@v4
      with:
        pattern: junit-test-results-${{github.run_id}}*
    - name: Publish Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: "**/build/test-results/test/TEST.xml"
        deduplicate_classes_by_file_name: true
