[project]
name = "codegen-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["codegen>=0.14.5", "mcp>=1.2.1"]

[tool.poetry.scripts]
codegen-mcp-server = "server:main"
