name: 'Run ATS'
description: 'Run Automated Test Selection to determine which tests to run'

inputs:
  default_tests:
    description: 'Default test path to run'
    required: true
  codecov_static_token:
    description: 'Codecov static token'
    required: true
  codecov_token:
    description: 'Codecov token'
    required: true
  collect_args:
    description: 'Additional arguments for test collection'
    required: false
    default: ''
  ats_collect_args:
    description: 'Additional arguments for ATS collection'
    required: false
    default: ''
  codecov_flags:
    description: 'Flags for codecov upload'
    required: false
    default: 'smart-tests'
  job_name:
    description: 'Name of the job for junit reporting'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run ATS
      shell: bash
      env:
        BASE_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
        DEFAULT_TESTS: ${{ inputs.default_tests }}
        CODECOV_STATIC_TOKEN: ${{ inputs.codecov_static_token }}
        CODECOV_TOKEN: ${{ inputs.codecov_token }}
        COLLECT_ARGS: ${{ inputs.collect_args }}
        ATS_COLLECT_ARGS: ${{ inputs.ats_collect_args }}
      run: |
        uv run codecovcli create-commit -t ${{ inputs.codecov_token }}
        uv run codecovcli create-report -t ${{ inputs.codecov_token }}
        bash ./.circleci/ats.sh

    - name: Run tests
      shell: bash
      run: |
        TESTS_TO_RUN=$(cat codecov_ats/tests_to_run.txt)
        echo $TESTS_TO_RUN | xargs uv run pytest --cov \
          -o junit_suite_name="${{ inputs.job_name }}" \
          -n auto \
          -vv \
          --cov \
          --cov-append \
          --cov-report=xml \
          ${{ inputs.collect_args }}

    - uses: ./.github/actions/actions/report
      with:
        flag: ${{ inputs.codecov_flags }}
