name: report
description: "Publish Test Reports"
inputs:
  flag:
    required: true
    description: "Relevant codecov flag"
runs:
  using: "composite"
  steps:
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/test-results/test/TEST.xml
      - name: Upload coverage reports to Codecov
        if: (success() || failure()) # always upload coverage reports even if the tests fail
        continue-on-error: true
        uses: codecov/codecov-action@v5.1.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: ${{ inputs.flag }}
          plugins: pycoverage,compress-pycoverage
