name: Cache Warm-Up

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"

jobs:

  warm-up-cache-uv:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check if on develop branch
        run: |
          if [ "${{ github.ref }}" != "refs/heads/develop" ]; then
            echo "Not on develop branch. Exiting."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop # Ensure we're operating on the 'develop' branch

      - name: Setup environment
        uses: ./.github/actions/setup-environment

  warm-up-cache:
    runs-on: ubuntu-latest
    needs: [warm-up-cache-uv]
    steps:
      - name: Check if on develop branch
        run: |
          if [ "${{ github.ref }}" != "refs/heads/develop" ]; then
            echo "Not on develop branch. Exiting."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop # Ensure we're operating on the 'develop' branch

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Cache oss-repos
        uses: ./.github/actions/setup-oss-repos
        with:
          CODEGEN_BOT_GHE_TOKEN: ${{ secrets.CODEGEN_BOT_GHE_TOKEN }}

      - name: Setup-pre-commit
        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - run: pre-commit install-hooks
        shell: bash
