name: (Legacy) Upload Python Package

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest-8, macos-latest ]
        python: [3.12, 3.13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup backend
        uses: ./.github/actions/setup-backend
        with:
          python-version: ${{ matrix.python }}

      - name: Build release distributions
        run: |
          uv build --wheel
        env:
          HATCH_BUILD_HOOKS_ENABLE: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Release to AWS codeartifact
        run: |
          export UV_PUBLISH_PASSWORD="$(aws codeartifact get-authorization-token --domain codegen --domain-owner 922078275900 --region us-east-1 --query authorizationToken --output text)"
          export UV_PUBLISH_USERNAME=aws
          uv publish --publish-url https://codegen-922078275900.d.codeartifact.us-east-1.amazonaws.com/pypi/codegen/
