name: Upload Python Package

on:
  push:
    tags:
      - v*
  workflow_dispatch:
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest-8, macos-latest]
        python: [3.12, 3.13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - name: Setup backend
        uses: ./.github/actions/setup-backend
        with:
          python-version: ${{ matrix.python }}
      - name: Get history and tags for SCM versioning to work
        run: |
          git branch
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Build release distributions
        run: |
          uv build --wheel
          uv build --package codegen-git --wheel
        env:
          HATCH_BUILD_HOOKS_ENABLE: true
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest-8
    permissions:
      contents: write
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
          pattern: wheels-*
      - name: Make github release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
          fail_on_unmatched_files: true
          generate_release_notes: true
