name: Unit Tests

on:
  push:
    branches:
      - "develop"
  pull_request:
    types: [ opened, synchronize, reopened, labeled ]
    branches:
      - "develop"
  workflow_dispatch:

jobs:
  test_codemods:
    # changing the following value will significantly affect github's billing. Be careful and consult with the team before changing it.
    runs-on: ubuntu-latest-32
    strategy:
      matrix:
        sync_graph: [ true, false ]
        size: [ small, large ]
        exclude:
          # Exclude large codemod tests when not needed
          - size: ${{(contains(github.event.pull_request.labels.*.name, 'big-codemod-tests') || github.event_name == 'push' || github.event_name == 'workflow_dispatch') && 'kevin' || 'large'}}
          - size: large
            sync_graph: true
    concurrency:
      group: ${{ github.workflow }}-${{github.ref}}-${{matrix.sync_graph}}-${{matrix.size}}-${{github.event_name == 'push'&& github.sha}}
      cancel-in-progress: true
    name: "Codemod tests ${{matrix.size}}: Sync Graph=${{matrix.sync_graph}}"
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{secrets.CODEGEN_BOT_SSH_KEY}}
      - run: |
          git lfs install
          git lfs pull
      - name: Setup backend
        uses: ./.github/actions/setup-backend
      - name: Cache oss-repos
        uses: ./.github/actions/setup-oss-repos
        with:
          CODEGEN_BOT_GHE_TOKEN: ${{ secrets.CODEGEN_BOT_GHE_TOKEN }}
      - name: Test with pytest
        timeout-minutes: 12
        run: |
          uv run pytest \
            -n auto \
            --size=${{matrix.size}} \
            --sync-graph=${{matrix.sync_graph}} \
            --token $CODEGEN_BOT_GHE_TOKEN \
            -o junit_suite_name="${{github.job}}" \
            tests/codemod/test_codemods.py::test_codemods_cloned_repos
        env:
          CODEGEN_BOT_GHE_TOKEN: ${{ secrets.CODEGEN_BOT_GHE_TOKEN }}
          GITHUB_WORKSPACE: $GITHUB_WORKSPACE
      - name: Install pycoverage
        run: |
          pip install coverage
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/test-results/test/TEST.xml
